[package]
name = "aes256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = { version = "0.10.3", features = ["heapless", "aes", "getrandom", "std"] }
anyhow = "1.0.82"
